version: '3.8'

services:
  node:
    image: lesson10angular:1.0
    container_name: lesson10angular_node_container
    ports:
      - '4200:4200'
    volumes:
      - ../:/home/node/app
      - node_modules_volume:/home/node/app/node_modules
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.node

volumes:
  node_modules_volume:
