FROM node:18.18.2-bullseye-slim

# Source
WORKDIR /home/node/app

# Requirements/configurations
RUN npm install -g @angular/cli@16.2.6
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN chown -R node:node /home/node/app
USER node

# Launch
CMD ["ng", "serve", "--host", "0.0.0.0"]
